diary/urls.py
from django.urls import path

from . import views

# diaryアプリケーションのルーティングにつける名前
app_name = 'diary'

urlpatterns = [
    # 初期ページ
    path('', views.IndexView.as_view(), name="index"),
    # 問い合わせページ
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    # 日記一覧表示
    path('diary-list/', views.DiaryListView.as_view(), name='diary_list'),
    #
]

private_diary/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from .import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    # http://<ホスト名>/〜の場合のルーティング
    path('', include('diary.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_URL)

diary/models.py
from django.db import models

from accounts.models import CustomUser


class Diary(models.Model):
    """日記モデル"""

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    Photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    Photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    Photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Diary'

    def __str__(self):
        return self.title

diary/forms.py
import os

from django import forms

from django.core.mail import EmailMessage

class InquiryForm(forms.Form):
    name = forms.CharField(label='name', max_length=30)
    email = forms.EmailField(label='e-mail')
    title = forms.CharField(label='title', max_length=30)
    message = forms.CharField(label='message', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class']='form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'input your name'

        self.fields['email'].widget.attrs['class']='form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'input your e-mail address'

        self.fields['title'].widget.attrs['class']='form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'input title'

        self.fields['message'].widget.attrs['class']='form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'input message'

    # メール送信メソッド
    def send_email(self):
        # 入力値の取得
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ{}'.format(title)
        message = '送信者名:{0}/nメールアドレス:{1}/nメッセージ:/n{2}'.format(name, email, message)
        # 送信元、送信先、ccは環境変数から取得
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [os.environ.get('FROM_EMAIL')]
        cc_list = [email]

        # EmailMessageインスタンスの作成
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

diary/views.py
import logging
import os


from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import InquiryForm
from .models import Diary

logger = logging.getLogger(__name__)


# 初期ページ
class IndexView(generic.TemplateView):
    # 表示するhtmlを指定
    template_name = "index.html"


# 問い合わせページ
class InquiryView(generic.FormView):
    # 表示するhtmlを指定
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')

    # form_validメソッドのoverride バリデーションに問題なかった場合、実行
    def form_valid(self, form):
        # form.pyのsend_mail()メソッド
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry send by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)


# 日記一覧表示ページ
class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = 'diary_list.html'
    paginate_by = 2

    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

diary/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet" />

    <!-- My style-->
    <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" style="text/css" />
    {% block head %}{% endblock %}
</head>

<body>
    <div id="wrapper">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'diary:index' %}">TOP PAGE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <!--問い合わせ-->
                        <li class="nav-item">
                            <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'diary:inquiry' %}">INQUIRY</a>
                        </li>
                        <!--日記一覧-->
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                            </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <!--ログアウト-->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <!--サインアップ-->
                        <li class="nav-item">
                            <a class="nav-link {% block active_signup %}{% endblock %}" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <!--ログイン-->
                        <li class="nav-item">
                            <a class="nav-link {% block active_login %}{% endblock %}" href="{% url 'account_login' %}">Log In</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block header %}{% endblock %}

        <!--変数messagesが空でない場合、表示 -->
        {% if messages %}
        <div class="container my-div-style">
            <div class="row">
                <ul class="messages" style="list-style: none;">
                    <!--messagesをループして表示-->
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% block contents %}
        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Hiro Inaba</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    </div>
    </body>
</html>

diary/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記一覧 | Private Diary {% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="#">新規作成</a>
            </div>
            {% for diary in diary_list %}
            <div class="post-preview">
                <a href="#">
                    <h2 class="post-title">
                        {{ diary.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ diary.content|truncatechars:20 }}
                    </h3>
                </a>
                <p class="post-meta">{{ diary.created_at }}</p>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>日記がありません。</p>
            {% endfor %}

            <!--ページネーション処理-->
            {% if is_paginated %}
            <ul class="pagination">
                <!--前ページへのリンク-->
                <% if page_obj.has_previous %>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <% endif %>

                <!--ページ数の表示-->
                {% for page_num in page_obj.paginator.page_range %}
                    {% if page_obj.number == page_num %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                    {% endfor %}
                {% endfor %}

                <!--次のページへのリンク-->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif % }
        </div>
    </div>
</div>
{% endblock %}

diary/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Private Diary{% endblock %}

{% block header %}
<header class="masthead text-center text-white'">
    <div class="masthead-content">
        <div class="container">
            <h2 class="masthead-heading mb-0">Inaba Web</h2>
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle1 bg-circle"></div>
    <div class="bg-circle2 bg-circle"></div>
    <div class="bg-circle3 bg-circle"></div>
    <div class="bg-circle4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg'%}">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">コンテンツ１</h2>
                    <p>説明</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg'%}">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">コンテンツ２</h2>
                    <p>説明</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg'%}">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">コンテンツ３</h2>
                    <p>説明</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}Inquiry Private Diary {% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">submit</button>
        </form>
    </div>
</div>
{% endblock %}